import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'theme-bg': 'var(--theme-bg)',
        'theme-bg-secondary': 'var(--theme-bg-secondary)',
        'theme-bg-tertiary': 'var(--theme-bg-tertiary)',
        'theme-card': 'var(--theme-card)',
        'theme-card-hover': 'var(--theme-card-hover)',
        'theme-card-secondary': 'var(--theme-card-secondary)',
        'theme-border': 'var(--theme-border)',
        'theme-border-hover': 'var(--theme-border-hover)',
        'theme-border-focus': 'var(--theme-border-focus)',
        'theme-text': 'var(--theme-text)',
        'theme-text-secondary': 'var(--theme-text-secondary)',
        'theme-text-muted': 'var(--theme-text-muted)',
        'theme-text-light': 'var(--theme-text-light)',
        'theme-primary': 'var(--theme-primary)',
        'theme-primary-hover': 'var(--theme-primary-hover)',
        'theme-primary-light': 'var(--theme-primary-light)',
        'theme-primary-bg': 'var(--theme-primary-bg)',
        'theme-primary-border': 'var(--theme-primary-border)',
        'theme-accent': 'var(--theme-accent)',
        'theme-accent-hover': 'var(--theme-accent-hover)',
        'theme-success': 'var(--theme-success)',
        'theme-success-bg': 'var(--theme-success-bg)',
        'theme-success-border': 'var(--theme-success-border)',
        'theme-danger': 'var(--theme-danger)',
        'theme-danger-bg': 'var(--theme-danger-bg)',
        'theme-danger-border': 'var(--theme-danger-border)',
        'theme-warning': 'var(--theme-warning)',
        'theme-warning-bg': 'var(--theme-warning-bg)',
        'theme-warning-border': 'var(--theme-warning-border)',
        'theme-info': 'var(--theme-info)',
        'theme-info-bg': 'var(--theme-info-bg)',
        'theme-info-border': 'var(--theme-info-border)',
        'theme-risk-on': 'var(--theme-risk-on)',
        'theme-risk-on-bg': 'var(--theme-risk-on-bg)',
        'theme-risk-off': 'var(--theme-risk-off)',
        'theme-risk-off-bg': 'var(--theme-risk-off-bg)',
        'theme-neutral': 'var(--theme-neutral)',
        'theme-neutral-bg': 'var(--theme-neutral-bg)',
        'theme-shadow': 'var(--theme-shadow)',
        'theme-shadow-hover': 'var(--theme-shadow-hover)',
        'theme-pattern-primary': 'var(--theme-pattern-primary)',
        'theme-pattern-secondary': 'var(--theme-pattern-secondary)',
        'theme-grid': 'var(--theme-grid)',
      },
      height: {
        'chart-sm': '300px',
        'chart-md': '400px',
        'chart-lg': '500px',
        'chart-xl': '600px',
      },
      minHeight: {
        'chart': '300px',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;