#!/bin/bash

# Railway Deployment Script
# Generated by Hive Mind Collective Intelligence System

set -e

echo "🚀 Starting Railway Deployment..."
echo "================================="

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "❌ Railway CLI not found. Please install it first:"
    echo "curl -sSL https://railway.app/install.sh | bash"
    exit 1
fi

echo "✅ Railway CLI found"

# Login check
if ! railway whoami &> /dev/null; then
    echo "🔑 Please login to Railway..."
    railway login
fi

echo "✅ Authenticated with Railway"

# Connect to project or create new
echo "🔌 Connecting to Railway project..."
if [ -z "$RAILWAY_PROJECT_ID" ]; then
    echo "📋 Creating new Railway project..."
    railway init
else
    echo "📋 Using existing project: $RAILWAY_PROJECT_ID"
    railway connect $RAILWAY_PROJECT_ID
fi

# Deploy services
echo "🚀 Deploying services to Railway..."

# Deploy backend services
echo "📦 Deploying FastAPI backend..."
railway service create fastapi-backend
railway up --service fastapi-backend --detach

echo "📦 Deploying Backtrader service..."
railway service create backtrader-service  
railway up --service backtrader-service --detach

echo "📦 Deploying frontend..."
railway service create frontend
railway up --service frontend --detach

# Add databases
echo "🗄️  Adding PostgreSQL database..."
railway add postgresql

echo "🔴 Adding Redis database..."  
railway add redis

# Set environment variables
echo "⚙️  Setting environment variables..."

# FastAPI service environment variables
railway variables set DATABASE_URL='${{Postgres.DATABASE_URL}}' --service fastapi-backend
railway variables set REDIS_URL='${{Redis.REDIS_URL}}' --service fastapi-backend
railway variables set TIINGO_API_KEY='36181da7f5290c0544e9cc0b3b5f19249eb69a61' --service fastapi-backend
railway variables set FRED_KEY='6f6919f0f4091f97951da3ae4f23d2b7' --service fastapi-backend
railway variables set SECRET_KEY='gayed-signals-railway-production-2025' --service fastapi-backend
railway variables set ENVIRONMENT='production' --service fastapi-backend
railway variables set PORT='${{PORT}}' --service fastapi-backend

# Backtrader service environment variables  
railway variables set DATABASE_URL='${{Postgres.DATABASE_URL}}' --service backtrader-service
railway variables set REDIS_URL='${{Redis.REDIS_URL}}' --service backtrader-service
railway variables set TIINGO_API_KEY='36181da7f5290c0544e9cc0b3b5f19249eb69a61' --service backtrader-service
railway variables set FRED_KEY='6f6919f0f4091f97951da3ae4f23d2b7' --service backtrader-service
railway variables set FLASK_ENV='production' --service backtrader-service
railway variables set PORT='${{PORT}}' --service backtrader-service

# Frontend environment variables
railway variables set NODE_ENV='production' --service frontend
railway variables set NEXT_TELEMETRY_DISABLED='1' --service frontend

echo "✅ Environment variables configured"

# Check deployment status
echo "🔍 Checking deployment status..."
sleep 30  # Wait for services to start

echo "📊 Service Status:"
railway status

# Get service URLs
echo "🌐 Service URLs:"
railway domain --service frontend
railway domain --service fastapi-backend  
railway domain --service backtrader-service

# Run health checks
echo "🏥 Running health checks..."

# Wait a bit more for services to be ready
sleep 30

BACKEND_URL=$(railway domain --service fastapi-backend 2>/dev/null || echo "")
BACKTRADER_URL=$(railway domain --service backtrader-service 2>/dev/null || echo "")

if [ ! -z "$BACKEND_URL" ]; then
    echo "Testing FastAPI backend: $BACKEND_URL"
    curl -f "$BACKEND_URL/health" || echo "⚠️  Backend health check failed"
fi

if [ ! -z "$BACKTRADER_URL" ]; then
    echo "Testing Backtrader service: $BACKTRADER_URL"  
    curl -f "$BACKTRADER_URL/health" || echo "⚠️  Backtrader health check failed"
fi

echo ""
echo "🎉 Railway deployment complete!"
echo "================================="
echo "✅ Frontend deployed and running"
echo "✅ Backend services deployed" 
echo "✅ Database services configured"
echo "✅ Environment variables set"
echo ""
echo "🔗 Access your application:"
railway domain --service frontend
echo ""
echo "📊 Monitor your services:"
echo "railway logs --service fastapi-backend"
echo "railway logs --service backtrader-service"
echo "railway logs --service frontend"
echo ""
echo "⚙️  Manage environment variables:"
echo "railway variables --service [service-name]"

exit 0