#!/bin/bash

# Vercel Environment Variables Setup Script
# Generated by Hive Mind Collective Intelligence System
# Uses values from existing .env file

set -e

echo "🚀 Setting up Vercel Environment Variables..."
echo "============================================="

# Load environment variables from .env file
if [ -f ".env" ]; then
    source .env
    echo "✅ Loaded variables from .env file"
else
    echo "❌ .env file not found. Please ensure you're in the project root."
    exit 1
fi

# Check if Vercel CLI is installed and logged in
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Please install it first:"
    echo "npm install -g vercel"
    exit 1
fi

if ! vercel whoami &> /dev/null; then
    echo "🔑 Please login to Vercel first:"
    echo "vercel login"
    exit 1
fi

echo "✅ Vercel CLI authenticated"

# Function to add Vercel environment variable
add_vercel_var() {
    local var_name=$1
    local var_value=$2
    local environment=${3:-"production"}
    
    if [ ! -z "$var_value" ]; then
        echo "Adding $var_name to $environment environment..."
        # Use echo to pipe the value to avoid interactive prompts
        echo "$var_value" | vercel env add "$var_name" "$environment" --force 2>/dev/null || echo "⚠️ Failed to add $var_name"
    fi
}

echo ""
echo "⚙️  Setting environment variables for production..."

# Runtime Environment
add_vercel_var "NODE_ENV" "production"
add_vercel_var "NEXT_TELEMETRY_DISABLED" "1"
add_vercel_var "VERCEL_ENV" "production"

# Financial Data APIs (from .env)
add_vercel_var "TIINGO_API_KEY" "$TIINGO_API_KEY"
add_vercel_var "ALPHA_VANTAGE_KEY" "$ALPHA_VANTAGE_KEY"
add_vercel_var "FRED_KEY" "$FRED_KEY"
add_vercel_var "BUREAU_OF_STATISTIC_KEY" "$BUREAU_OF_STATISTIC_KEY"

# AI & ML Services (from .env)
add_vercel_var "OPENAI_API_KEY" "$OPENAI_API_KEY"
add_vercel_var "ANTHROPIC_API_KEY" "$ANTHROPIC_API_KEY"
add_vercel_var "GEMINI_API_KEY" "$GEMINI_API_KEY"

# Additional Data Sources (from .env)
add_vercel_var "PERPLEXITY_API_KEY" "$PERPLEXITY_API_KEY"
add_vercel_var "SUPABASE_API_KEY" "$SUPABASE_API_KEY"
add_vercel_var "QDRANT_API_KEY" "$QDRANT_API_KEY"
add_vercel_var "PUBMED_API_KEY" "$PUBMED_API_KEY"
add_vercel_var "GNEWS_API_KEY" "$GNEWS_API_KEY"
add_vercel_var "REDDIT_API_KEY" "$REDDIT_API_KEY"

# External Service URLs (Railway backend)
add_vercel_var "PYTHON_SERVICE_URL" "https://backend-production-0a4c.up.railway.app"
add_vercel_var "FASTAPI_BASE_URL" "https://backend-production-0a4c.up.railway.app"

# External Database URLs (Railway managed)
add_vercel_var "DATABASE_URL" "postgresql://postgres:password@postgres.railway.app:5432/production"
add_vercel_var "REDIS_URL" "redis://redis.railway.app:6379"

# Security (using .env values)
add_vercel_var "SECRET_KEY" "$SECRET_KEY"
add_vercel_var "JWT_SECRET_KEY" "jwt-vercel-production-2025"

# CORS Configuration
add_vercel_var "ALLOWED_ORIGINS" "https://gayed-signals-dashboard-alpirwn5h-philippe-beliveaus-projects.vercel.app"
add_vercel_var "CORS_ORIGINS" "https://gayed-signals-dashboard-alpirwn5h-philippe-beliveaus-projects.vercel.app"

# Vercel Serverless Optimizations
add_vercel_var "MAX_ANALYSIS_TIME" "30"
add_vercel_var "MAX_REQUEST_TIMEOUT" "25"
add_vercel_var "CHART_GENERATION_TIMEOUT" "20"
add_vercel_var "VERCEL_FUNCTION_TIMEOUT" "30"

# Performance Settings (from .env)
add_vercel_var "INITIAL_CAPITAL" "$INITIAL_CAPITAL"
add_vercel_var "LOG_LEVEL" "$LOG_LEVEL"

# Feature Flags
add_vercel_var "ENABLE_CACHING" "true"
add_vercel_var "CACHE_TTL" "1800"
add_vercel_var "SAFLA_ENABLED" "true"

echo ""
echo "⚙️  Setting environment variables for preview environment..."

# Add key variables to preview environment as well
add_vercel_var "NODE_ENV" "preview" "preview"
add_vercel_var "TIINGO_API_KEY" "$TIINGO_API_KEY" "preview"
add_vercel_var "FRED_KEY" "$FRED_KEY" "preview"
add_vercel_var "OPENAI_API_KEY" "$OPENAI_API_KEY" "preview"
add_vercel_var "PYTHON_SERVICE_URL" "https://backend-production-0a4c.up.railway.app" "preview"

echo ""
echo "⚙️  Setting environment variables for development environment..."

# Add key variables to development environment
add_vercel_var "NODE_ENV" "development" "development"
add_vercel_var "TIINGO_API_KEY" "$TIINGO_API_KEY" "development"
add_vercel_var "FRED_KEY" "$FRED_KEY" "development"
add_vercel_var "PYTHON_SERVICE_URL" "http://localhost:5000" "development"
add_vercel_var "FASTAPI_BASE_URL" "http://localhost:8002" "development"

echo ""
echo "📊 Checking Vercel environment variables..."
vercel env ls

echo ""
echo "🎉 Vercel environment variables setup complete!"
echo "==============================================="
echo "✅ Production environment: All API keys configured"
echo "✅ Preview environment: Key variables configured"
echo "✅ Development environment: Local development configured"
echo "✅ External services: Railway backend URLs configured"
echo ""
echo "🔍 Verify your configuration:"
echo "vercel env ls"
echo ""
echo "🚀 Deploy to Vercel:"
echo "vercel --prod"
echo ""
echo "🧪 Test your deployment:"
echo "curl https://gayed-signals-dashboard-alpirwn5h-philippe-beliveaus-projects.vercel.app/api/health"

exit 0